FROM golang:latest

WORKDIR /app

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY ./Auth_Server/server.go ./
COPY ./proto/ ./proto/

RUN go build -o ./Auth_Server



EXPOSE 5052

CMD ["./Auth_Server"]